language: node_js
node_js:
- 9
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python3.2 python2.7

python:
 - "2.7"

install:
  - pip install 'requests[security]'
  - pip install --user awscli
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: camtowns-first-site
  local-dir: ./
  skip_cleanup: true
  region: us-east-2
  on:
    branch: master