language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
  - pip install --user awscli
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: camtowns-first-site
  local-dir: build
  skip_cleanup: true
  region: us-east-2
  on:
    branch: master

script:
  - npm test
  - npm run build